### ISSUE TITLE
BINSEC 0.11.0 fails to build with 4.14.1

### ISSUE THREAD

**Issue by nmeum** [binsec/binsec#60]
I maintain a [BINSEC package](https://packages.guix.gnu.org/packages/binsec) for [Guix](https://guix.gnu.org). Guix still uses ocaml 4.14.1 by default. According to BINSEC's [installation instructions](https://github.com/binsec/binsec/blob/0.11.0/INSTALL.md), it requires ocaml >= 4.14, hence it should compile. However, when upgrading the Guix package from 0.10.1 to 0.11.0 I get the following compilation error:

```
(cd _build/default && /gnu/store/fjbbnpnf4wchw62883z8s6jpjd3vsap3-ocaml-4.14.1/bin/ocamlc.opt -w -40 -g -bin-annot -I src/base/.binsec_base.objs/byte -I /gnu/store/6b2bsf662ssszkbh7yjkn0ahx4kkcswk-ocaml-zarith-1.12/lib/ocaml/site-lib/zarith -I src/domain/.binsec_domains.objs/public_cmi -intf-suffix .ml -no-alias-deps -open Binsec_base -o src/base/.binsec_base.objs/byte/binsec_base__Basic_types.cmo -c -impl src/base/basic_types.ml)
File "src/base/basic_types.ml", line 156, characters 22-41:
156 |     let to_bigint x = Z.of_int32_unsigned x
                            ^^^^^^^^^^^^^^^^^^^
Error: Unbound value Z.of_int32_unsigned
(cd _build/default && /gnu/store/fjbbnpnf4wchw62883z8s6jpjd3vsap3-ocaml-4.14.1/bin/ocamlc.opt -w -40 -g -bin-annot -I src/base/.binsec_base.objs/byte -I /gnu/store/6b2bsf662ssszkbh7yjkn0ahx4kkcswk-ocaml-zarith-1.12/lib/ocaml/site-lib/zarith -I src/domain/.binsec_domains.objs/public_cmi -intf-suffix .ml -no-alias-deps -open Binsec_base -o src/base/.binsec_base.objs/byte/binsec_base__Virtual_address.cmo -c -impl src/base/virtual_address.ml)
File "src/base/virtual_address.ml", line 28, characters 15-34:
28 | let to_int32 = Z.to_int32_unsigned
                    ^^^^^^^^^^^^^^^^^^^
Error: Unbound value Z.to_int32_unsigned
(cd _build/default && /gnu/store/fjbbnpnf4wchw62883z8s6jpjd3vsap3-ocaml-4.14.1/bin/ocamlopt.opt -w -40 -g -I src/base/.binsec_base.objs/byte -I src/base/.binsec_base.objs/native -I /gnu/store/6b2bsf662ssszkbh7yjkn0ahx4kkcswk-ocaml-zarith-1.12/lib/ocaml/site-lib/zarith -I src/domain/.binsec_domains.objs/native -I src/domain/.binsec_domains.objs/public_cmi -intf-suffix .ml -no-alias-deps -open Binsec_base -o src/base/.binsec_base.objs/native/binsec_base__Basic_types.cmx -c -impl src/base/basic_types.ml)
File "src/base/basic_types.ml", line 156, characters 22-41:
156 |     let to_bigint x = Z.of_int32_unsigned x
                            ^^^^^^^^^^^^^^^^^^^
Error: Unbound value Z.of_int32_unsigned
```

Unfortunately, I don't know any ocaml myself but since BINSEC 0.10.1 compiled fine, it seems to me that 0.11.0 is maybe no longer compatible with ocaml 4.14.X?

**Comment by nmeum** [comment]
Oh! I didn't notice that the dependencies were bumped in the `0.11.0` release, updating `Zarith` package does fix the issue. Thanks for pointing that out, I will submit an update for the BINSEC Guix package shortly then :)
